AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Validation hooks for the service deployed on ECS Fargate 

Parameters:
  ApiName:
    Type: String

  DomainName:
    Type: String

  Port:
    Type: Number
    Default: 9000

Resources:
  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - 'CodeDeployHook_'
          - !Ref ApiName
          - '_pre-traffic'
      CodeUri: ./
      Timeout: 300
      Handler: pre-traffic-hook.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
              - "codedeploy:CreateCloudFormationDeployment"
            Resource:
              !Sub 'arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:*/*'
      Runtime: nodejs10.x
      DeploymentPreference:
        Enabled: false
        Role: ""
      Environment:
        Variables:
          TargetUrl: !Join # Example: https://api.your-domain.com:9000/color
            - ''
            - - 'https://'
              - !Ref DomainName
              - ':'
              - !Ref Port
              - '/color'

  CodeDeployHookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: "Invoke-Hooks"
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - "lambda:InvokeFunction"
            Resource: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:CodeDeployHook_*'
