version: 0.2

# S3_BUCKET is passed from pipeline.yaml

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - node --version
      - npm --version
      - echo "Build started on $(date)"
  build:
    commands:
      - echo [PHASE] Entered the build phase...
      - npm install 
      - aws cloudformation package --template-file cloudformation/infrastructure/cf-template.yaml --s3-bucket "$S3_BUCKET" --output-template-file packaged-template.yaml
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - packaged-template.yaml
    - node_modules
