AWSTemplateFormatVersion: 2010-09-09
Description: The CloudFormation template for the CodePipeline.

Parameters:
  ServiceName:
    Type: String

Resources:

  # Create an S3 Bucket to store build artifacts
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref ServiceName, !Ref "AWS::AccountId", "s3bucket"]]

  # TODO: create CodeBuild and CodePipeline